baseURL = "https://oliviergoulet.dev/"
locale = "en-ca"
title = "Olivier Goulet"

[taxonomies]
  tag = "tags"

[build]
  writeStats = true

[markup]
  [markup.highlight]
    style = "tokyonight-night"
    lineNos = true

[[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menus.main]]
  name = "Posts"
  pageRef = "/posts"
  weight = 20

